/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/Teelevision/excommerce/go"
)

func main() {
	log.Printf("Server started")

	CartsAPIService := openapi.NewCartsAPIService()
	CartsAPIController := openapi.NewCartsAPIController(CartsAPIService)

	OrdersAPIService := openapi.NewOrdersAPIService()
	OrdersAPIController := openapi.NewOrdersAPIController(OrdersAPIService)

	ProductsAPIService := openapi.NewProductsAPIService()
	ProductsAPIController := openapi.NewProductsAPIController(ProductsAPIService)

	UsersAPIService := openapi.NewUsersAPIService()
	UsersAPIController := openapi.NewUsersAPIController(UsersAPIService)

	router := openapi.NewRouter(CartsAPIController, OrdersAPIController, ProductsAPIController, UsersAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
