/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"errors"
)

// ProductsAPIService is a service that implents the logic for the ProductsApiServicer
// This service should implement the business logic for every endpoint for the ProductsApi API.
// Include any external packages or services that will be required by this service.
type ProductsAPIService struct {
}

// NewProductsAPIService creates a default api service
func NewProductsAPIService() ProductsAPIServicer {
	return &ProductsAPIService{}
}

// GetAllProducts - Get all products
func (s *ProductsAPIService) GetAllProducts() (interface{}, error) {
	// TODO - update GetAllProducts with the required logic for this service method.
	// Add api_products_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetAllProducts' not implemented")
}

// StoreCouponForProduct - Create product coupon
func (s *ProductsAPIService) StoreCouponForProduct(productID string, couponCode string, coupon Coupon) (interface{}, error) {
	// TODO - update StoreCouponForProduct with the required logic for this service method.
	// Add api_products_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'StoreCouponForProduct' not implemented")
}
