/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A OrdersApiController binds http requests to an api service and writes the service results to the http response
type OrdersApiController struct {
	service OrdersApiServicer
}

// NewOrdersApiController creates a default api controller
func NewOrdersApiController(s OrdersApiServicer) Router {
	return &OrdersApiController{ service: s }
}

// Routes returns all of the api route for the OrdersApiController
func (c *OrdersApiController) Routes() Routes {
	return Routes{ 
		{
			"CreateOrderFromCart",
			strings.ToUpper("Post"),
			"/beta/carts/{cartId}/prepareOrder",
			c.CreateOrderFromCart,
		},
		{
			"PlaceOrder",
			strings.ToUpper("Post"),
			"/beta/orders/{orderId}/place",
			c.PlaceOrder,
		},
	}
}

// CreateOrderFromCart - Create order from cart
func (c *OrdersApiController) CreateOrderFromCart(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	cartId := params["cartId"]
	order := &Order{}
	if err := json.NewDecoder(r.Body).Decode(&order); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.CreateOrderFromCart(cartId, *order)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// PlaceOrder - Place order
func (c *OrdersApiController) PlaceOrder(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	orderId := params["orderId"]
	result, err := c.service.PlaceOrder(orderId)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
