/*
 * EXCommerce
 *
 * EXCommerce is an example shop system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"ProductsGet",
			strings.ToUpper("Get"),
			"/beta/products",
			c.ProductsGet,
		},
	}
}

// ProductsGet - 
func (c *DefaultApiController) ProductsGet(w http.ResponseWriter, r *http.Request) { 
	result, err := c.service.ProductsGet()
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
