/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Address - An address of a person, company or similar.
type Address struct {

	// The name of the person, company or similar.
	Name string `json:"name"`

	// The ISO 3166-1 alpha-2 country code.
	Country string `json:"country"`

	// The postal code code.
	PostalCode string `json:"postalCode"`

	// The city.
	City string `json:"city"`

	// The street name, number and any suffixes.
	Street string `json:"street"`
}
