/*
 * EXCommerce
 *
 * EXCommerce is an example shop system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Product - A product of the shop.
type Product struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
