/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Coupon - A coupon for a product that can be used during checkout.
type Coupon struct {

	// The coupon display text.
	Name string `json:"name"`

	// The case-insensitive coupon code.
	Code string `json:"code"`

	// The discount in percent on the product price.
	Discount int32 `json:"discount"`

	Product Product `json:"product"`

	// The time when this coupon exires. If omitted the server chooses a time in the future.
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
}
