/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Order - An order.
type Order struct {

	// The UUID of the order.
	ID string `json:"id"`

	// The status of the order.
	Status string `json:"status"`

	// The total price of this order.
	Price float32 `json:"price"`

	Buyer Address `json:"buyer"`

	Recipient Address `json:"recipient"`

	Coupons []string `json:"coupons,omitempty"`

	Positions []Position `json:"positions"`
}
