/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Product - A product of the shop.
type Product struct {

	// The UUID of the product. If a product has no id it is a virtual product, like a discount, and only for displaying purposes.
	Id string `json:"id,omitempty"`

	// The display name of the product.
	Name string `json:"name"`

	// The price of a single item of the product.
	Price float32 `json:"price,omitempty"`
}
