/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MalformedInputError - The input is invalid.
type MalformedInputError struct {

	// A human-readable message about what went wrong.
	Message string `json:"message"`

	// A JSON Pointer to the incorrect input value.
	Pointer string `json:"pointer"`
}
