/*
 * ExCommerce
 *
 * ExCommerce is an example commerce system.
 *
 * API version: beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// LoginForm - Login form
type LoginForm struct {
	Name Name `json:"name"`

	Password string `json:"password"`
}
